### ISSUE TITLE
Improve Ceph documentation

### ISSUE THREAD

**Issue by vickmp** [OpenNebula/one-deploy#45]
**Description**
Some sections should be updated adding more info and context for more Ceph uses cases:
- Add a description on how to add disks devices to the inventory and dedicated devices as well.
- Add a warning comment to wiping out all the disks added to the inventory prior the execution of the one-deploy tool. Some advises [here](https://docs.ceph.com/en/quincy/cephadm/services/osd/#deploy-osds).
- Add a Troubleshooting/Basic Operations section with information on how to remove an OSD and how to create additional pools (with potentially different replicas, PGS, etc...) after the installation.

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by rsmontero** [comment]
https://github.com/OpenNebula/one-deploy/wiki/arch_single_ceph
