### ISSUE TITLE
Fix Debian repository URL

### ISSUE THREAD

**Issue by acidroper** [OpenNebula/one-deploy#47]
**Description**
When attempting to install OpenNebula on Debian 11.9, the following error occurs:

```
FAILED! => {"changed": false, "msg": "Failed to update apt cache: W:Updating from such a repository can't be done securely, and is therefore disabled by default., W:See apt-secure(8) manpage for repository creation and user configuration details., E:The repository 'https://downloads.opennebula.io/repo/6.8.0/Debian/11.9 stable Release' does not have a Release file."}
```

It happens because of using `{{ ansible_distribution_version }}` in Debian repository URL template in the task "Install OpenNebula package source". As a result, the following source string is generated:

`deb https://downloads.opennebula.io/repo/6.8.0/Debian/11.9 stable opennebula`

But the OpenNebula repository doesn't have this path.

To resolve this, I suggest using `ansible_distribution_major_version` Ansible variable in order to get the correct source string:

`deb https://downloads.opennebula.io/repo/6.8.0/Debian/11 stable opennebula`

**To Reproduce**
Run the installation on Debian 11.9 or any other Debian minor version release.

**Details**
 - Ansible version: `2.16.5`
 - Linux OS distro in your cluster: `Debian 11.9`
 - Version: `996af7f`

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by sk4zuzu** [comment]
@acidroper thank you for reporting this. I believe the PR we merged should solve the problem. :+1:

**Comment by acidroper** [comment]
@sk4zuzu the problem is solved. Thanks!
