### ISSUE TITLE
the playbook: opennebula.deploy.main could not be found

### ISSUE THREAD

**Issue by figueirav** [OpenNebula/one-deploy#68]
When I run the command 
 ansible-playbook -i inventory/example.yml opennebula.deploy.main

I  keep getting the error 

ansible-playbook -i inventory/example.yml opennebula.deploy.main

Can anyone help me?

**Comment by sk4zuzu** [comment]
Hi @figueirav

I believe `ansible-playbook -i inventory/example.yml opennebula.deploy.main` is not an error message, it's just a command.

1. What kind of OS do you use inside the ansible controller machine?
2. How did you install ansible-playbook?
3. What is the version reported by ansible-playbook?
4. How did you clone one-deploy repo, directly or via ansible-galaxy?
5. Did you modify `inventory/example.yml`? Does it match your infrastructure?
